config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true
  validates :start_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  
  def count
    @schedules_count = Schedule.all.count
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  before_action :count
  
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to(schedules_path)
    else
      render "new", status: 422
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo))
      flash[:notice] = "スケジュールを編集しました"
      redirect_to(schedules_path)
    else
      flash.now[:notice] = "スケジュールの編集ができませんでした"
      render "edit", status: 422
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to(schedules_path, status: :see_other)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>

    <%= yield %>

  </body>
</html>

app/views/schedules/edit.html.erb
<h3>スケジュール編集</h3>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= render "shared/error", obj:@schedule %>

<%= form_with model:@schedule, local: true do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date, "終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日" %></th>
      <td><%= f.check_box :all_day %><br>終日の場合はチェックを入れます</td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "編集する" %></li>
      <li><%= link_to("スケジュール一覧に戻る", schedules_path) %></li>
    </ul>
  </div>
<% end %>

<footer>
  <h1>今日の日付：<%= Date.today.strftime("%Y年%m月%d日") %></h1>
</footer>

app/views/schedules/index.html.erb
<h3>スケジュール一覧</h3>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.start_date.strftime("%Y年%m月%d日") %></td>
        <td><%= schedule.end_date.strftime("%Y年%m月%d日") %></td>
        <td>
          <% if schedule.all_day %>
            ○
          <% end %>
        </td>
        <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to("確認", schedule_path(schedule)) %></td>
        <td><%= link_to "編集", edit_schedule_path(schedule) %></td>
        <td><%= link_to "削除", schedule_path(schedule), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="link"><%= link_to("スケジュール新規登録", new_schedule_path) %></p>

<footer>
  <h1>今日の日付：<%= Date.today.strftime("%Y年%m月%d日") %>　　スケジュール合計：<%= @schedules_count %></h1>
</footer>

app/views/schedules/new.html.erb
<h3>スケジュール新規作成</h3>

<%= render "shared/error", obj:@schedule %>

<%= form_with model:@schedule, local: true do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start_date, "開始日" %></th>
      <td><%= f.date_field :start_date %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date, "終了日" %></th>
      <td><%= f.date_field :end_date %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日" %></th>
      <td><%= f.check_box :all_day %><br>終日の場合はチェックを入れます</td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "新規登録", class: "new_submit" %></li>
      <li><%= link_to("スケジュール一覧に戻る", schedules_path) %></li>
    </ul>
  </div>
<% end %>

<footer>
  <h1>今日の日付：<%= Date.today.strftime("%Y年%m月%d日") %></h1>
</footer>

app/views/schedules/show.html.erb
<h3>スケジュール詳細</h3>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>投稿日時</th>
    <td><%= @schedule.created_at.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start_date.strftime("%Y年%m月%d日") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.end_date.strftime("%Y年%m月%d日") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td>
      <% if @schedule.all_day %>
        ○
      <% end %>
    </td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to("スケジュール一覧に戻る", schedules_path) %></li>
    <li><%= link_to "スケジュールを編集する", edit_schedule_path(@schedule) %></li>
    <li><%= link_to "スケジュールを削除する", schedule_path(@schedule), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></li>
  </ul>
</div>

<footer>
  <h1>今日の日付：<%= Date.today.strftime("%Y年%m月%d日") %></h1>
</footer>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>